# Generated by Django 4.2.5 on 2023-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Carrer"), (2, "Owner"), (3, "Admin")],
                null=True,
            ),
        ),
    ]
