# Generated by Django 4.2.5 on 2023-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_address_alter_user_email_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
