# Generated by Django 4.2.5 on 2023-11-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(db_column="postalCode", max_length=15),
        ),
    ]
