# Generated by Django 4.2.5 on 2023-11-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_address_postal_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="phone_number",),
        migrations.AddField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(
                blank=True, db_column="phoneNumber", max_length=15, null=True
            ),
        ),
    ]
