# Generated by Django 4.2.5 on 2023-11-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_user_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(model_name="address", name="postal_code",),
        migrations.AddField(
            model_name="address",
            name="postalCode",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="firstName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="lastName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
