# Generated by Django 4.2.5 on 2023-11-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_remove_address_postal_code_address_postalcode_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address", old_name="postalCode", new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="user", old_name="phoneNumber", new_name="phone_number",
        ),
        migrations.RemoveField(model_name="user", name="firstName",),
        migrations.RemoveField(model_name="user", name="lastName",),
    ]
