# Generated by Django 4.2.5 on 2023-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
