# Generated by Django 4.2.5 on 2024-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
