# Generated by Django 4.2.5 on 2024-01-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
