# Generated by Django 4.2.5 on 2024-01-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
