# Generated by Django 4.2.5 on 2024-01-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
